#MONGODB SERVER CONFIGURATIONS (for docker-compose.yml)
ALLOW_EMPTY_PASSWORD: no
MONGODB_PORT_NUMBER: ${PROD_MONGODB_PORT_NUMBER}
MONGODB_ENABLE_JOURNAL: false
MONGODB_ENABLE_DIRECTORY_PER_DB: yes
MONGODB_ROOT_USER: ${PROD_MONGODB_ROOT_USER}
MONGODB_ROOT_PASSWORD: ${PROD_MONGODB_ROOT_PASSWORD}

#MONGODB Spring Configurations (for application to startup)
MONGODB_HOST_NAME: ${PROD_MONGODB_HOST_MAME}
MONGODB_AUTH_DATABASE: ${PROD_MONGODB_AUTH_DATABASE}

mongodb:
  trusted:
    host: ${MONGODB_HOST_NAME}
    port: ${MONGODB_PORT_NUMBER}
    database: ${PROD_MONGODB_TRUSTED_DATABASE}
    authenticationDatabase: ${MONGODB_AUTH_DATABASE}
    username: ${PROD_MONGODB_TRUSTED_USERNAME}
    password: ${PROD_MONGODB_TRUSTED_PASSWORD}
  remote:
    host: ${MONGODB_HOST_NAME}
    port: ${MONGODB_PORT_NUMBER}
    database: ${PROD_MONGODB_REMOTE_DATABASE}
    authenticationDatabase: ${MONGODB_AUTH_DATABASE}
    username: ${PROD_MONGODB_REMOTE_USERNAME}
    password: ${PROD_MONGODB_REMOTE_PASSWORD}

app:
  client:
    id: ${PROD_ASSISTANT_CLIENT_ID}
    secret: ${PROD_ASSISTANT_CLIENT_SECRET}
    redirect: ${PROD_ASSISTANT_CLIENT_REDIRECT}