#MONGODB SERVER CONFIGURATIONS (for docker-compose.yml)
ALLOW_EMPTY_PASSWORD: no
MONGODB_PORT_NUMBER: 27015
MONGODB_ENABLE_JOURNAL: false
MONGODB_ENABLE_DIRECTORY_PER_DB: yes
MONGODB_ROOT_USER: mongoroot
MONGODB_ROOT_PASSWORD: WL6B0tPAssw0rd

#MONGODB Spring Configurations (for application to startup)
MONGODB_HOST_NAME: mongodb
MONGODB_AUTH_DATABASE: admin

mongodb:
  trusted:
    host: ${MONGODB_HOST_NAME}
    port: ${MONGODB_PORT_NUMBER}
    database: trusted
    username: trusted_user
    password: trusted_user_secret_super_password
    authenticationDatabase: ${MONGODB_AUTH_DATABASE}
  remote:
    host: ${MONGODB_HOST_NAME}
    port: ${MONGODB_PORT_NUMBER}
    database: remote
    username: remote_user
    password: remote_user_secret_super_password
    authenticationDatabase: ${MONGODB_AUTH_DATABASE}

app:
  client:
    id: 3toh7ur3q0vlzbqtovdgg4zfnc6kp3
    secret: 1j21360uuw0je8cgmxg79ex93y8l1g
    redirect: http://localhost:15610/auth

  logging:
    file:
      enabled: false
